--
-- PostgreSQL database dump
--

-- Dumped from database version 10.21
-- Dumped by pg_dump version 10.21

-- Started on 2022-09-19 16:38:39

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 1 (class 3079 OID 12924)
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- TOC entry 2857 (class 0 OID 0)
-- Dependencies: 1
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 202 (class 1259 OID 23273)
-- Name: ARMDataSources; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ARMDataSources" (
    "ID" uuid NOT NULL,
    "DataSourceID" text NOT NULL,
    "DataSourceDesc" text,
    "DataSourceURL" text,
    "DataSourceFormat" text,
    "IsActive" boolean NOT NULL,
    "IsMasterData" boolean,
    "IsDataSyncActive" boolean DEFAULT false NOT NULL,
    "DataSyncInterval" integer,
    "LastSyncedOn" timestamp without time zone,
    "CreatedOn" timestamp without time zone,
    "UpdatedOn" timestamp without time zone,
    "DataSyncInitFormat" text,
    "AllowAnonymousAccess" boolean DEFAULT false NOT NULL,
    "ARMDataSourceID" uuid,
    "AppName" text DEFAULT ''::text NOT NULL,
    "DataSyncAPIList" text,
    "selectedDataSyncDataSources" uuid[],
    "selectedUserGroups" uuid[]
);


ALTER TABLE public."ARMDataSources" OWNER TO postgres;

--
-- TOC entry 197 (class 1259 OID 23201)
-- Name: ARMDefinations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ARMDefinations" (
    "ID" uuid NOT NULL,
    "Type" text NOT NULL,
    "DefinitionID" text NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "DefinitionHTML" text NOT NULL,
    "DataSource" text,
    "CreatedOn" timestamp without time zone,
    "UpdatedOn" timestamp without time zone,
    "AllowAnonymousAccess" boolean DEFAULT false NOT NULL,
    "AppName" text DEFAULT ''::text NOT NULL,
    "DataSources" text[],
    "selectedUserGroups" uuid[]
);


ALTER TABLE public."ARMDefinations" OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 23315)
-- Name: ARMSignInUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ARMSignInUsers" (
    "Id" uuid NOT NULL,
    "UserName" text NOT NULL,
    "Password" text NOT NULL
);


ALTER TABLE public."ARMSignInUsers" OWNER TO postgres;

--
-- TOC entry 198 (class 1259 OID 23209)
-- Name: ARMUserGroups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ARMUserGroups" (
    "ID" uuid NOT NULL,
    "AppName" text NOT NULL,
    "Name" text NOT NULL,
    "AuthType" integer NOT NULL,
    "ApprovalType" integer NOT NULL,
    "ExternalAuthMethod" text NOT NULL,
    "ExternalAuthUrl" text NOT NULL,
    "ExternalAuthRequest" text NOT NULL,
    "ExternalAuthResponse" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "Roles" text[]
);


ALTER TABLE public."ARMUserGroups" OWNER TO postgres;

--
-- TOC entry 199 (class 1259 OID 23217)
-- Name: ARMUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ARMUsers" (
    "ID" uuid NOT NULL,
    "AppName" text NOT NULL,
    "UserName" text NOT NULL,
    "Password" text NOT NULL,
    "Email" text NOT NULL,
    "MobileNo" text,
    "UserGroupId" uuid NOT NULL,
    "UserGroup" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "InsertedOn" timestamp without time zone,
    "ActivatedOn" timestamp without time zone
);


ALTER TABLE public."ARMUsers" OWNER TO postgres;

--
-- TOC entry 201 (class 1259 OID 23227)
-- Name: NotificationTemplate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."NotificationTemplate" (
    "Id" integer NOT NULL,
    "AppName" text NOT NULL,
    "TemplateId" text NOT NULL,
    "TemplateString" text NOT NULL
);


ALTER TABLE public."NotificationTemplate" OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 23225)
-- Name: NotificationTemplate_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."NotificationTemplate" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."NotificationTemplate_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 196 (class 1259 OID 23172)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 2848 (class 0 OID 23273)
-- Dependencies: 202
-- Data for Name: ARMDataSources; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."ARMDataSources" VALUES ('04c4010e-8a65-4afc-a2bd-ca9cbda42d7e', 'loaddata', 'LoadData REST API', 'http://192.168.2.12/runscripts/ASBTStructrest.dll/datasnap/rest/TASBTstruct/loaddata', '{"emailGateway":{"txthostname":"smtp.gmail.com","txtportno":"8867","txtuserid":"deepti@compunnel.com"},"SMSGateway":{"userto":"8876352637","userfrom":"9878632345","message":"Hii deepti"},"WhatsappLogin":{"Mobile":"7865456789","AuthCode":"87878"},"AdminInstance":{"admin":"diipttiisngh","Password":"agilelabs8"},"Keys":{"KeyInterval":15,"PrivateKey":"BE3utMyG1jdfg2Za"}} ', true, NULL, false, 12, NULL, NULL, '2022-09-05 17:59:58.339384', '{"result":[{"result":{"status":"Success"}}]}', true, NULL, 'APP', NULL, '{04c4010e-8a65-4afc-a2bd-ca9cbda42d7e,9ad9d388-84af-456e-945f-a2d808013b33}', '{55a41e8b-236a-472f-942a-74dfacb4b87f,2aeb75d2-bf40-45df-8e0c-596703204938}');
INSERT INTO public."ARMDataSources" VALUES ('9ad9d388-84af-456e-945f-a2d808013b33', 'op_medication_durationLists', 'Prescription', 'http://192.168.2.12/runscripts/ASBTStructrest.dll/datasnap/rest/TASBTstruct/loaddata', '{"appTitle":"WA","appName":"Msg","appLogo":null,"appColor":"#563d7c","userGroup":"Grp1","txtRoles":"Rol1","txtAPI":"Rol1","txtDataSource":"DS1"}', false, NULL, true, 15, NULL, NULL, '2022-09-05 18:00:21.129956', 'result{  sucess :"true"}', false, NULL, 'Testdeep', NULL, '{9ad9d388-84af-456e-945f-a2d808013b33}', '{7f0d11b6-0b0e-4197-b577-2a136209dfaa}');
INSERT INTO public."ARMDataSources" VALUES ('6c117da0-01f7-4d72-8c0d-54345ec44f7a', 'TestId', 'TestAxpert', 'http://192.168.2.12/Datasource/API', '"WA": {  "appName": "Msg",  "appLogo": null,  "appColor": "#563d7c",  "userGroup": "Grp1",  "txtRoles": "Rol1",  "txtAPI": "Rol1",  "txtDataSource": "DS1"},', true, NULL, false, 30, NULL, NULL, '2022-09-05 18:00:30.13545', 'result{  statusCode=200}', false, NULL, 'SecureAxpert', NULL, '{04c4010e-8a65-4afc-a2bd-ca9cbda42d7e}', '{1e89084e-94a2-4f86-adb3-2b6aec17b8ad}');


--
-- TOC entry 2843 (class 0 OID 23201)
-- Dependencies: 197
-- Data for Name: ARMDefinations; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."ARMDefinations" VALUES ('36e4121c-1ba0-4601-8da7-b8fb615af97f', 'Form', 'OP_Consultation', 'OP Consultation', 'Test', '<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="EMR - Kauvery ">
    <meta name="keywords" content="EMR - Home">
    <meta name="author" content="Kauvery Hospital">
    <link rel="shortcut icon" href="../StaticFiles/img/favicon.png">
    <title>OP EMR</title>
    <link href="../StaticFiles/fonts/icofont.min.css" rel="stylesheet" type="text/css" />
    <link href="../StaticFiles/fonts/font-awesome1/css/all.min.css" rel="stylesheet" type="text/css" />
    <link href="../StaticFiles/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="../StaticFiles/css/color-kau.css" rel="stylesheet" type="text/css" />
    <link href="../StaticFiles/css/op-patient-page.css" rel="stylesheet" type="text/css" />
    <link href="../StaticFiles/css/mul-steps.css" rel="stylesheet" type="text/css" />
    <link href="../StaticFiles/css/bootstrap-select.min.css" rel="stylesheet" type="text/css" />
    <link href="../StaticFiles/css/toggle-switch.css" rel="stylesheet">
    <link href="../StaticFiles/css/select2.min.css" rel="stylesheet" />
    <link href="../StaticFiles/css/multi-select.css" rel="stylesheet">
    <link href="../StaticFiles/css/modal-pop.css" rel="stylesheet">
    <link href="../StaticFiles/css/jquery-ui.css" rel="stylesheet" type="text/css" />
    <link href="../StaticFiles/css/responsive.css" rel="stylesheet" type="text/css" />
    <link href="../StaticFiles/css/pages-ui.css" rel="stylesheet" type="text/css" />
    <link href="../StaticFiles/css/op_patientdashboard.css" rel="stylesheet" type="text/css" />
    <!-- start new edit -->
    <link href="../StaticFiles/css/toastmaker.min.css" rel="stylesheet" type="text/css">
    <style>
        .material-icons i,
        .dr-name {
            color: #8b3365;
        }

        #clickloader {
            background: none repeat scroll 0 0 black;
            position: fixed;
            display: block;
            opacity: 0.5;
            z-index: 1000001;
            left: 0;
            top: 0;
            height: 100%;
            width: 100%;
        }

        #clickloader i {
            left: 45%;
            top: 45%;
            position: absolute;
            color: #ffffff73;
        }
    </style>

    <!-- end new edit -->
</head>

<body class="page-header-fixed">
    <div class="d-flex justify-content-center bgloader mainloader"
        style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; opacity: 1; background-color: #e1e1e1;">
        <div class="spinner-border text-danger" style="margin-top: 30%;" role="status"><span
                class="visually-hidden"></span>
        </div>
    </div>

    <div class="page-wrapper">
        <div class="page-header navbar navbar-fixed-top">
            <div class="page-header-inner">
                <div class="row headbootctrl">
                    <div class="col-md-auto col-lg-auto backtitle">
                        <div class="navbar-left">
                            <h2><i class="icofont-arrow-left ax-openinline" data-target-mobile="OPEMR-PatientList"
                                    data-target="OPEMR-PatientList" data-target-params="" data-elem="#divHome"></i></h2>
                        </div>
                        <div class="info-box-icon mt-2 pname-initial">
                            <div class="material-icons fs-4">A</div>
                        </div>
                    </div>
                    <div class="col-md-10 col-lg-8  backtitle">
                        <div class="overflow-hidden">
                            <div class="row gx-1 ax-data" data-source="op_patientdashboard_header">
                                <div class="col-lg-9 col-md-12">
                                    <div class="p-1">

                                        <div class="row g-1 bootct-pname">
                                            <div class="col-6">
                                                <div class="p-0 text-truncate">
                                                    <Strong>
                                                        <axdata>op_number</axdata>,&nbsp;<axdata>patient_name</axdata>
                                                        ,&nbsp;<axdata>age_sex</axdata>,&nbsp;
                                                    </Strong>
                                                </div>
                                            </div>
                                            <div class="col-2">
                                                <div class="p-0 text-truncate"><i class="icofont-phone"></i>
                                                    <axdata>mobileno</axdata>,
                                                </div>
                                            </div>
                                            <div class="col-4">
                                                <div class="p-0 text-truncate"><i class="icofont-email"></i>&nbsp;<span>
                                                        <axdata>email</axdata>
                                                    </span></div>
                                            </div>
                                            <div class="col-auto">
                                                <div class="p-0">Booking date: <span class="fw-bold">
                                                        <axdata>booking_date</axdata>
                                                    </span>,</div>
                                            </div>
                                            <div class="col-6">
                                                <div class="p-0">App Date & Time : <span class="fw-bold">
                                                        <axdata>appointment_date</axdata>
                                                    </span></div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-12 d-md-none d-lg-block">
                                    <div class="p-1 text-truncate">Referred by <br />
                                        <axdata>ref_doctor</axdata>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                    <div class="col-lg-2 col-md-10 titlectrl">
                        <div class="row mt-3">
                            <div class="col-lg-2 col-md-auto">
                                <div class="material-icons mdl-badge mdl-badge--overlap">
                                    <i class="fa fa-bell fs-4" aria-hidden="true"></i>
                                    <span class="badge bg-secondary">0</span>
                                </div>
                            </div>
                            <div class="col-lg-10 col-md-auto text-truncate fs-5  p-0 ps-3"><span>Hi,</span> <span
                                    class="dr-name ax-data" data-source="op_username">
                                    <axdata>user_name</axdata>
                                </span></div>
                        </div>
                    </div>
                    <div class="col-md-auto logctrl"> <i class="fas fa-sign-out-alt my-4 fs-4 ax-logout"></i> </div>
                </div>
            </div>
        </div>
        <div class="page-container">
            <div class="page-content-wrapper">
                <div class="page-content">
                    <div class="row">
                        <div class="col-xl-11 col-md-10 mt-2 mb-1 cirpatop">
                            <div class="ax-hidden" id="op_consultation_start"></div>
                            <button type="button" class="btn  bg-light btn-xs ax-save"
                                data-target="op_consultation_start" id="startConsult"><i
                                    class="icofont-play-alt-1"></i>Start Consult
                            </button>
                            <button type="button" class="btn  bg-light btn-xs ax-save"
                                data-target="op_consultation_start" id="teleConsult"><i class="icofont-video"></i>Tele
                                Consult </button>
                            <button type="button" class="btn  bg-light btn-xs load-send_doc" id="sendDoc"><i
                                    class="icofont-paper-plane"></i>Send Doc </button>
                            <button type="button" class="btn  bg-light btn-xs load-upload_doc" id="uploadDocbtn"><i
                                    class="icofont-upload"></i>Upload
                                Docs </button>
                            <!-- <button type="button" class="btn  bg-light btn-xs ax-openpopup"
                            data-popup-iframeUrl="opd_prescription_print" data-popup-iframeClass="frame-ctrl-min" data-popup-title="Print Prescription" id="printDoc"><i
                                    class="icofont-print"></i>Print Docs
                            </button> -->

                            <button type="button" class="btn  bg-light btn-xs" id="printDoc" onclick="opdprescription()"><i
                                    class="icofont-print"></i>Print Docs
                            </button>
                            <button type="button" class="btn  bg-light btn-xs load-view_doc" id="viewDocbtn"><i
                                    class="icofont-search-document"></i>View Docs
                            </button>
                        </div>
                        <div class="col-xl-1 col-md-2 mt-2 on-offline">
                            <select id="onlineStatus" data-show-content="true" class="pull-right form-control">
                                <option
                                    data-content="<span class=''text-success''><i class=''fa fa-circle'' aria-hidden=''true''></i></span> Online"
                                    value="T">&nbsp;</option>
                                <option
                                    data-content="<span class=''text-warning''><i class=''fa fa-circle'' aria-hidden=''true''></i></span> Offline"
                                    value="F">&nbsp;</option>
                            </select>
                            <div id="op_set_doctorstatus">
                                <button type="button" id="setDocStatus" class="ax-hidden ax-save"
                                    data-target="op_set_doctorstatus" data-bs-dismiss="modal"></button>
                            </div>
                        </div>
                    </div>

                    <span id="clickloader" style="display: none;">
                        <i class="fa fa-spinner fa-4x fa-spin"></i>
                    </span>

                    <div id="opd_print_prescription" style="display:none;"></div>


                    <div class="row gx-0 histroyctrl tele-innerctrl" id="content">
                        <button type="button" class="ax-refreshhtml loadPatient-dbdata" id="initialassessmentctrl_ref"
                            data-refresh="true" data-target="op_initialassessment" style="display:none"></button>
                        <div class="col-md-4 col-xl-3">
                            <div class="card">
                                <div class="card-header">
                                    <span class="pull-left"><i class="icofont-tasks"></i></span>&nbsp;
                                    <span>Initial Assessment</span>
                                    <a class="pull-right load-iniassment text-white"><i
                                            class="icofont-plus-circle"></i></a>
                                </div>
                                <div class="card-body" id="op_initialassessment">
                                    <div class="comscr">
                                        <ul class="ax-repeat-innerhtml ax-data"
                                            data-source="op_patientdashboard_initialassessment">
                                            <li><span>
                                                    <axdata>sdesc</axdata>
                                                </span> : <span class="fbold">
                                                    <axdata>s_values</axdata>
                                                </span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 col-xl-3">
                            <button type="button" class="ax-refreshhtml loadPatient-dbdata consultation-ref"
                                id="consultation-ref" data-refresh="true" data-target="op_consultationdetails"
                                style="display:none"></button>
                            <div class="card">
                                <div class="card-header">
                                    <span class="pull-left"><i class="icofont-doctor-alt"></i></span>&nbsp;
                                    <span>Consultation Details</span>
                                    <a class="pull-right load-consultation text-white"><i
                                            class="icofont-plus-circle"></i></a>
                                </div>
                                <div class="card-body" id="op_consultationdetails">
                                    <div class="comscr">
                                        <ul class="ax-data" data-source="op_patientdashboard_consultationdetails">
                                            <li><span>Present complaints: </span><span class="fbold">
                                                    <axdata>presentcomplaints</axdata>
                                                </span></li>
                                            <li><span>Clinical Findings: </span><span class="fbold">
                                                    <axdata>clinicalifinding</axdata>
                                                </span></li>
                                            <li><span>Diagnosis: </span><span class="fbold">
                                                    <axdata>dignosis</axdata>
                                                </span></li>
                                            <li><span>General Advice: </span><span class="fbold">
                                                    <axdata>general_advice</axdata>
                                                </span></li>
                                            <li><span>Diet Advice: </span><span class="fbold">
                                                    <axdata>diet_advice</axdata>
                                                </span></li>
                                            <li><span class="fbold">
                                                    <axdata>ip_dmissionis_required</axdata>
                                                </span></li>
                                            <li><span class="fbold">
                                                    <axdata>surgery_required</axdata>
                                                </span></li>
                                            <li><span>Current Investigation requests: </span><span class="fbold">
                                                    <axdata>investigation</axdata>
                                                </span></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 col-xl-3">
                            <div class="card">
                                <div class="card-header">
                                    <span class="pull-left"><i class="icofont-history"></i></span>&nbsp;
                                    <span>Past Visit History</span>
                                    <span class="pull-right">
                                        <!--<button type="button" class="btn  btn-xs bg-light">View</button>-->
                                    </span>
                                </div>
                                <div class="card-body">
                                    <div class="comscr">
                                        <div class="noti-information notification-menu">
                                            <div class="notification-list not-list ax-repeat-innerhtml ax-data"
                                                data-source="op_patientdashboard_pastvisithistory">
                                                <a href="javascript:;" class="single-mail"><span class="icon opipround">
                                                        <axdata>visit_type</axdata>
                                                    </span>
                                                    <span>
                                                        <axdata>doctorname</axdata>,<axdata>speciality</axdata> on
                                                        <axdata>sdate</axdata>
                                                    </span>
                                                    <span class="notificationtime">
                                                        <div><span>Complaints/Case Type</span> : <span class="tx-bold">
                                                                <axdata>case_type</axdata>
                                                            </span></div>
                                                    </span>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <button type="button" class="ax-refreshhtml" id="btnVitalsChange" data-refresh="true"
                            data-target="vitalsDetails" style="display:none"></button>
                        <div class="col-md-4 col-xl-3" id="vitalsDetails">
                            <div class="card ax-data" data-source="op_patientdashboard_vitals">
                                <div class="card-header">
                                    <span class="pull-left"><i class="icofont-heart-beat"></i></span>&nbsp;
                                    <span>Vitals</span>&nbsp;<span>(<axdata>vital_datetime</axdata>)</span>
                                    <a class="pull-right text-white load-vitals"><i class="icofont-plus-circle"></i></a>
                                </div>
                                <div class="card-body">
                                    <div class="comscr">
                                        <div class="row bor-b">
                                            <div class="col-xl-6">BP :</div>
                                            <div class="col-xl-6"><strong class="va-orange">
                                                    <axdata>bp</axdata>
                                                </strong>
                                            </div>
                                        </div>
                                        <div class="row bor-b">
                                            <div class="col-xl-6">HR/Pulse :</div>
                                            <div class="col-xl-6"><strong>
                                                    <axdata>pulserate</axdata>
                                                </strong></div>
                                        </div>
                                        <div class="row bor-b">
                                            <div class="col-xl-6">Temp :</div>
                                            <div class="col-xl-6"><strong class="va-orange">
                                                    <axdata>temprature</axdata>
                                                </strong>
                                            </div>
                                        </div>
                                        <div class="row bor-b">
                                            <div class="col-xl-6">SpO2 :</div>
                                            <div class="col-xl-6"><strong class="va-orange">
                                                    <axdata>spo</axdata>
                                                </strong>
                                            </div>
                                        </div>
                                        <div class="row bor-b">
                                            <div class="col-xl-6">BMI :</div>
                                            <div class="col-xl-6"><strong>
                                                    <axdata>bmi</axdata>
                                                </strong></div>
                                        </div>
                                        <div class="row bor-b">
                                            <div class="col-xl-6">HIP :</div>
                                            <div class="col-xl-6"><strong>
                                                    <axdata>hip</axdata>
                                                </strong></div>
                                        </div>
                                        <div class="row bor-b">
                                            <div class="col-xl-6">Waist :</div>
                                            <div class="col-xl-6"><strong>
                                                    <axdata>waist</axdata>
                                                </strong></div>
                                        </div>
                                        <div class="row bor-b">
                                            <div class="col-xl-6">Height :</div>
                                            <div class="col-xl-6"><strong>
                                                    <axdata>height</axdata>
                                                </strong></div>
                                        </div>
                                        <div class="row bor-b">
                                            <div class="col-xl-6">Weight :</div>
                                            <div class="col-xl-6"><strong>
                                                    <axdata>weight</axdata>
                                                </strong></div>
                                        </div>
                                        <div class="row bor-b">
                                            <div class="col-xl-6">BMI Remarks :</div>
                                            <div class="col-xl-6"><strong>
                                                    <axdata>bmi_remarks</axdata>
                                                </strong></div>
                                        </div>
                                        <div class="row bor-b">
                                            <div class="col-xl-6">W/H Ratio :</div>
                                            <div class="col-xl-6"><strong>
                                                    <axdata>wh_ratio</axdata>
                                                </strong></div>
                                        </div>
                                        <div class="row bor-b">
                                            <div class="col-xl-6">W/H Ratio Remarks :</div>
                                            <div class="col-xl-6"><strong>
                                                    <axdata>wh_ratio_remarks</axdata>
                                                </strong></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                        <div class="col-md-4 col-xl-3">
                            <div class="card">
                                <div class="card-header">
                                    <span class="pull-left"><i class="icofont-laboratory"></i></span>&nbsp;
                                    <span>Lab Results</span>
                                    <span class="pull-right">
                                        <!--<button type="button" class="btn  btn-xs bg-light" data-bs-toggle="modal"
                      data-bs-target="#labtable">Table</button>
                    <button type="button" class="btn  btn-xs bg-light">Trends</button>-->
                                    </span>
                                </div>
                                <div class="card-body">
                                    <div class="comscr ulctrl-lab ax-repeat-innerhtml ax-data"
                                        data-source="op_patientdashboard_labresults">

                                        <div class="row border-bottom">
                                            <div><strong>
                                                    <axdata>servicename</axdata>
                                                </strong></div>
                                            <div>
                                                <axdata>sdate</axdata>,&nbsp; <span>Order No. <axdata>service_order</axdata></span>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 col-xl-3">
                            <div class="card">
                                <div class="card-header">
                                    <span class="pull-left"><i class="icofont-prescription"></i></span>&nbsp;
                                    <span>Radiology Results</span>
                                    <span class="pull-right">&nbsp;</span>
                                </div>
                                <div class="card-body">
                                    <div class="comscr ">
                                        <ul class="ax-repeat-innerhtml ax-data"
                                            data-source="op_patientdashboard_radiologyresults">
                                            <li class="text-decoration-underline"><span>
                                                    <axdata>servicename</axdata>
                                                </span> -
                                                <span>
                                                    <axdata>investigationdate</axdata>
                                                </span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 col-xl-3">
                            <button type="button" class="ax-refreshhtml loadPatient-dbdata consultation-ref"
                                id="medicinectrl_ref" data-refresh="true" data-target="op_consultationdetails_nextrev"
                                style="display:none"></button>
                            <div class="card">
                                <div class="card-header">
                                    <span class="pull-left"><i class="icofont-search-document"></i></span>&nbsp;
                                    <span>Next Review Details</span>
                                    <span class="pull-right">&nbsp;</span>
                                </div>
                                <div class="card-body" id="op_consultationdetails_nextrev">
                                    <div class="comscr ulctrl-lab ax-data" data-source="op_patientdashboard_nextreview">

                                        <div><span>Next Review On: </span><span class="fbold">
                                                <axdata>sdate</axdata>
                                            </span>
                                        </div>
                                        <div class="text-decoration-underline">Review Investigations</div>
                                        <ul>
                                            <li>-<strong>
                                                    <axdata>servicename</axdata>
                                                </strong></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 col-xl-3">
                            <button type="button" class="ax-refreshhtml loadPatient-dbdata consultation-ref"
                                id="medicinectrl_ref" data-refresh="true"
                                data-target="op_consultationdetails_medication" style="display:none"></button>
                            <div class="card">
                                <div class="card-header">
                                    <span class="pull-left"><i class="icofont-tablets"></i></span>&nbsp;
                                    <span>Medication</span>
                                    <span class="pull-right"><i class="icofont-printer"></i></span>
                                </div>
                                <div class="card-body" id="op_consultationdetails_medication">
                                    <div class="comscr ulctrl-lab ax-repeat-innerhtml ax-data"
                                        data-source="op_patientdashboard_medication">
                                        <div class="text-decoration-underline">
                                            <axdata>doctor</axdata>
                                        </div>
                                        <ul>
                                            <li>
                                                <axdata>medicine</axdata>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 col-xl-3">
                            <button type="button" class="ax-refreshhtml loadPatient-dbdata consultation-ref"
                                id="medicinectrl_ref" data-refresh="true"
                                data-target="op_consultationdetails_opinioncross" style="display:none"></button>
                            <div class="card">
                                <div class="card-header">
                                    <span class="pull-left">&nbsp;</span>&nbsp;
                                    <span>Opinion / Cross Consultation</span>
                                    <span class="pull-right">&nbsp;</span>
                                </div>
                                <div class="card-body" id="op_consultationdetails_opinioncross">
                                    <div class="comscr">
                                        <ul class="ax-repeat-innerhtml ax-data"
                                            data-source="op_patientdashboard_opinion">
                                            <li class="text-decoration-underline">
                                                <span>
                                                    <axdata>doctor_shrt</axdata>
                                                </span>, <span>
                                                    <axdata>speciality</axdata>, <axdata>visitedon</axdata>
                                                </span>
                                            </li>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-4 col-xl-3">
                            <div class="card">
                                <div class="card-header">
                                    <span class="pull-left">&nbsp;</span>&nbsp;
                                    <span>Patient Uploaded Documents</span>
                                    <span class="pull-right">&nbsp;</span>
                                </div>
                                <div class="card-body">
                                    <div class="comscr">
                                        <!--<ul>
                      <li><span class="text-decoration-underline text-primary">Prescription1.png</span>
                        :
                        <span>15/09/2021,03:45 pm</span></li>
                    </ul>-->
                                        <ul>
                                            <li><span>No documents available</span></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>






    <!-- start initial assesment popup -->

    <div class="modal fade" id="initialAssessmentModal" data-bs-keyboard="false" data-bs-backdrop="static">
        <div class="modal-dialog frame-ctrl-desk">
            <div class="modal-content">
                <div class="modal-header bg-kauvery">
                    <h5 class="modal-title" id="">Initial Assessment</h5>
                    <button type="button" class="model-close" onclick="onInitAssessmentClose()" aria-label="Close"><i
                            class="icofont-close-line"></i></button>
                </div>
                <div class="modal-body">
                    <iframe id="initial-ass" name="myIframe" frameborder="5" class="frame-ctrl"></iframe>
                </div>
            </div>
        </div>
    </div>
    <!-- end initial assesment popup -->

    <!-- start consultation popup -->

    <div class="modal fade" id="consultationiframe" data-bs-keyboard="false" data-bs-backdrop="static">
        <div class="modal-dialog frame-ctrl-desk">
            <div class="modal-content">
                <div class="modal-header bg-kauvery">
                    <h5 class="modal-title" id="">Consultation details</h5>
                    <button type="button" class="model-close" onclick="onConsultationClose()" aria-label="Close"><i
                            class="icofont-close-line"></i></button>
                </div>
                <div class="modal-body">
                    <iframe id="consultation_load" name="myIframe" frameborder="5" class="frame-ctrl"></iframe>
                </div>
            </div>
        </div>
    </div>
    <!-- end consultation popup -->

    <!-- start Vitals popup -->
    <div class="modal fade" id="vitals-capture" data-bs-keyboard="false" data-bs-backdrop="static">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header bg-kauvery">
                    <h5 class="modal-title" id="">Vitals details</h5>
                    <button type="button" class="model-close" data-bs-dismiss="modal" aria-label="Close"><i
                            class="icofont-close-line"></i></button>
                </div>
                <div class="modal-body">
                    <iframe id="vitals_load" name="myIframe" frameborder="5" class="frame-ctrl"></iframe>
                </div>
            </div>
        </div>
    </div>
    <!-- end Vitals popup -->


    <!-- Visit history modal -->
    <div class="modal fade" id="visitHistoryModal" data-bs-keyboard="false" data-bs-backdrop="static">
        <div class="modal-dialog frame-ctrl-desk">
            <div class="modal-content">
                <div class="modal-header  primaryBgColor text-light p-1 px-2">
                    <h5 class="modal-title ms-3" id="exampleModalCenterTitle">View History</h5>
                    <button type="button" class="border-0 bg-transparent" data-bs-dismiss="modal" class="close"
                        aria-label="Close">
                        <span class="btn btn-danger btn-sm cancelBorder  px-2 py-1" aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <iframe id="visit_history_pop" name="myIframe" frameborder="5" class="frame-ctrl"></iframe>
                </div>
            </div>
        </div>
    </div>

    <!-- view doc modal -->
    <div class="modal fade" id="viewDoc" data-bs-keyboard="false" data-bs-backdrop="static">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header  primaryBgColor text-light p-1 px-2">
                    <h5 class="modal-title ms-3" id="exampleModalCenterTitle">View Document</h5>
                    <button type="button" class="border-0 bg-transparent" data-bs-dismiss="modal" class="close"
                        aria-label="Close">
                        <span class="btn btn-danger btn-sm cancelBorder  px-2 py-1" aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <iframe id="view_doc_pop" name="myIframe" frameborder="5" class="frame-ctrl-min"></iframe>
                </div>
            </div>
        </div>
    </div>

    <!-- Upload doc modal -->
    <div class="modal fade" id="uploadDoc" data-bs-keyboard="false" data-bs-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header  primaryBgColor text-light p-1 px-2">
                    <h5 class="modal-title ms-3" id="exampleModalCenterTitle">Upload Document</h5>
                    <button type="button" class="border-0 bg-transparent" data-bs-dismiss="modal" class="close"
                        aria-label="Close">
                        <span class="btn btn-danger btn-sm cancelBorder  px-2 py-1" aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <iframe id="upload_doc_pop" name="myIframe" frameborder="5" class="frame-ctrl-min"></iframe>
                </div>
            </div>
        </div>
    </div>


    <!-- Send doc modal -->
    <div class="modal fade" id="sendDocument" data-bs-keyboard="false" data-bs-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header  primaryBgColor text-light p-1 px-2">
                    <h5 class="modal-title ms-3" id="exampleModalCenterTitle">Send Document</h5>
                    <button type="button" class="border-0 bg-transparent" data-bs-dismiss="modal" class="close"
                        aria-label="Close">
                        <span class="btn btn-danger btn-sm cancelBorder  px-2 py-1" aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <iframe id="send_doc_pop" name="myIframe" frameborder="5" class="frame-ctrl-min"></iframe>
                </div>
            </div>
        </div>
    </div>



    <!-- Start Lab popup -->
    <div class="modal fade" id="labtable" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-kauvery">
                    <h5 class="modal-title " id="staticBackdropLabel">Lab Results Table</h5>
                    <button type="button" class="model-close" data-bs-dismiss="modal" aria-label="Close"><i
                            class="icofont-close-line"></i></button>
                </div>

                <div class="modal-body labtable">
                    <table class="table  table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">Date</th>
                                <th scope="col">FBS</th>
                                <th scope="col">PFBS</th>
                                <th scope="col">RFBS</th>
                                <th scope="col">HbA1c</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">06/09/21</th>
                                <td>110</td>
                                <td>110</td>
                                <td>110</td>
                                <td>110</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer justify-content-center add-colctrl">
                    <button type="button" class="btn btn-light">Save</button>
                </div>
            </div>
        </div>

    </div>

    <div class="modal fade" id="axPopupModal" data-bs-keyboard="false" data-bs-backdrop="static">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header  primaryBgColor text-light p-1 px-2">
                    <h5 class="modal-title ms-3" id="axPopupTitle"></h5>
                    <button type="button" class="border-0 bg-transparent" data-bs-dismiss="modal" class="close"
                        aria-label="Close">
                        <span class="btn btn-danger btn-sm cancelBorder  px-2 py-1" aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <iframe id="axPopupIFrame" name="myIframe" frameborder="5" class=""></iframe>
                </div>
            </div>
        </div>
    </div>

    <!-- End Lab popup -->

    <script src="../StaticFiles/js/jquery.min.js"></script>
    <script src="../StaticFiles/js/jquery-ui.js"></script>
    <script src="../StaticFiles/js/popper.min.js"></script>
    <script src="../StaticFiles/js/bootstrap.min.js"></script>
    <script src="../StaticFiles/js/select2.min.js"></script>
    <script src="../StaticFiles/js/mul-step.js"></script>
    <script src="../StaticFiles/js/bootstrap-select.min.js"></script>
    <script src="../StaticFiles/js/op-patient-page.js?v=1.2"></script>
    <script src=''../StaticFiles/Js/AxpertConnect.js?v=1.5''></script>

    <!-- start new edit -->
    <script src="../StaticFiles/js/toastmaker.min.js"></script>

    <script>
        function showbg() {
            var loader = document.getElementById("clickloader");
            loader.style.display = ''block'';
        }
        function hidebg() {
            var loader = document.getElementById("clickloader");
            loader.style.display = ''none'';
        }
        function opdprescription() {
            showbg();
            var div = document.getElementById("opd_print_prescription");
            div.innerHTML = ''<iframe src="Popup?load=opd_prescription_print" ></iframe>'';
            const myTimeout = setTimeout(hidebg, 2000);
        }
    </script>
</body>

</html>', NULL, NULL, '2022-09-05 23:11:10.347548', false, 'SecureAxpert', NULL, '{5f80254b-8dbe-4e84-8410-676b5f489ad7,7f0d11b6-0b0e-4197-b577-2a136209dfaa}');
INSERT INTO public."ARMDefinations" VALUES ('57d73494-4498-4ba5-97f7-a26143ecd803', 'List', 'InstantOper', 'InstantOper', 'Test', '<!DOCTYPE html>
<html>
<body>

<p>Agile Connect</p>
</body>
</html>

', NULL, NULL, '2022-09-05 23:11:52.957023', true, 'WA', NULL, '{1e89084e-94a2-4f86-adb3-2b6aec17b8ad,2aeb75d2-bf40-45df-8e0c-596703204938}');
INSERT INTO public."ARMDefinations" VALUES ('8325b97f-776e-45af-8f03-31fd11768efd', 'List', 'AgileAxpert', 'TitleAxpert', 'AxperTesting', '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta name="description" content="KMC EMR" />
    <meta name="author" content="KMC" />
    <title>EMR - KMC</title>
    <link href="../StaticFiles/fonts/icofont.min.css" rel="stylesheet" type="text/css"/>
      <link href="../StaticFiles/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	<link href="../StaticFiles/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="../StaticFiles/css/extra_pages.css"  rel="stylesheet" />
	<link href="../StaticFiles/css/material.min.css" rel="stylesheet" />
	
    <link href="../StaticFiles/css/toastmaker.min.css" rel="stylesheet" type="text/css">
   <!-- start new edit -->
	<style>
	   .focus-input100 i{ bottom: 2px;}
	   .wrap-login100 {  padding: 15px 55px 15px 55px; }
	   .input100 { height: 31px;}
	   .wrap-input100 { margin-bottom: 17px;}
	   .toastmaker { min-width: 450px !important;}
      /*.btn:focus { background-color: #8c8e8f !important;}*/
	  .btn:focus {
    background-color: #8b3365 !important;
    box-shadow: 0 0 0 0.25rem #f9fafb;
    color: #fff;}
	</style>
  <!-- end new edit -->
 </head>
<body class="page-header-fixed sidemenu-closed-hidelogo page-content-white page-md header-white dark-color logo-dark" >
    
	<div class="limiter">
		<div class="container-login100 page-background">
  <!-- end new edit -->
  
			<div class="wrap-login100">
				<form class="login100-form validate-form">
					<span class="login100-form-logo">
						<img src="../StaticFiles/emrui/img/Kauvery_Hospital_logo.png">
					</span>
					<div class="wrap-input100 mt-5" >
						<input class="input100" type="text" id="username" placeholder="User Name">
						<span class="focus-input100" ><i class="icofont-doctor"></i></span>
					</div>
					<div class="wrap-input100 " >
						<span class="focus-input100"><i class="icofont-lock"></i></span>
						<input  class="input100 toggle-password" id="password" type="password"  placeholder="Password" >
						<span class="input-group-addon toggle-password pull-right"><i class="fa fa-eye-slash"></i></span>
					</div>
					<div class="wrap-input100 " >
					   <div class="form-group selectemr">
						<span class="focus-input100"><i class="icofont-patient-file"></i></span>
						<select class="form-control" id="usergroup">
                               <option value="34e65a41-3539-4f0c-8cd4-2aa55237b1dd">OP EMR</option>
                               <option value="00000000">IP EMR</option>
                             </select>
						<span class="input-group-addon toggle-password pull-right"><i class="icofont-rounded-down"></i></span>
					   </div>
					</div>
					<div class="container-login100-form-btn">
					   <div class="row mt-3">
					      <div class="col-md-6 col-xs-6"><button class="btn btn-xs bg-white text-rose btn-block px-5" type="button" id="login"><strong>Login</strong></button></div>
					     <!-- <div class="col-md-6 col-xs-6"><button class="btn btn-xs bg-white text-rose btn-block">Reset</button></div>-->
					   </div>
					</div>
					 <div class="text-center pt-5 text-white">Application Version - 1.0.2 beta</div>
				</form>
			</div>
		</div>
	</div>
	
    <script src="../StaticFiles/js/jquery.min.js" ></script>
    <script src="../StaticFiles/js/bootstrap.min.js"></script>
	<script src="../StaticFiles/js/MD5.js"></script>
	<script src="../StaticFiles/js/login2.js"></script>
    <script src="../StaticFiles/js/toastmaker.min.js"></script>
<script>
  $(''document'').ready(function(){
  $(''#usergroup'').prop(''disabled'', true);
  });
 function CallLoginAPI(){
 
      if($("#username").val()== ''''){
	      ToastMaker(''User name empty'');
		  return false;
	  }
	  if($("#password").val()== ''''){
	      ToastMaker(''Password empty'');
		  return false;
	  }
	  if($("select#usergroup option:selected").val()== ''''){
	      ToastMaker(''Login selection mandatory'');
		  return false;
	  }
 
	var loginObj = new Login($("#username").val(), MD5($("#password").val()), $(''#usergroup option:selected'').val());

	$.ajax({
		type: "POST",
		url: loginURL,
		cache: false,
		async: true,
		contentType: "application/json;charset=utf-8",
		data: JSON.stringify(loginObj),
		dataType: "text",
		success: function (token) {
			//console.log(token);
			localStorage.setItem("RCP_JwtToken", "Bearer " + token);
			localStorage.setItem("AxpertConnectUser", $("#username").val());
			window.location.href = "home";
		},
		error: function (request, status, error) {
			ToastMaker(''Invalid username / password'');
		}
	});
}
 
</script>

</body>
</html>', NULL, NULL, '2022-09-05 23:12:05.549687', false, 'FB', NULL, '{55a41e8b-236a-472f-942a-74dfacb4b87f,5f80254b-8dbe-4e84-8410-676b5f489ad7}');


--
-- TOC entry 2849 (class 0 OID 23315)
-- Dependencies: 203
-- Data for Name: ARMSignInUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."ARMSignInUsers" VALUES ('76657b40-757e-4d5e-8aff-5868ec6aac24', 'diiptiiSingh', 'Abcd@12345');


--
-- TOC entry 2844 (class 0 OID 23209)
-- Dependencies: 198
-- Data for Name: ARMUserGroups; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."ARMUserGroups" VALUES ('7f0d11b6-0b0e-4197-b577-2a136209dfaa', 'FB', 'Marketing', 100, 1, 'AuthenticateIden', 'TestUrl', 'EXTAuthRequest', 'Responsedatas', true, '{employee,"Finance Admin"}');
INSERT INTO public."ARMUserGroups" VALUES ('55a41e8b-236a-472f-942a-74dfacb4b87f', 'TestApp2', 'Admin', 100, 1, 'ThirdPartyAuthentication', 'TestUrl', 'RequestedDaTAS', 'Responsedatas', true, '{"Finance Admin","HR L4"}');
INSERT INTO public."ARMUserGroups" VALUES ('2aeb75d2-bf40-45df-8e0c-596703204938', 'APP', 'IT Advisor', 400, 2, 'AuthenticateId', 'ExtURL', 'RequestedDaata', 'Response', true, '{"HR L4","HR L2"}');
INSERT INTO public."ARMUserGroups" VALUES ('5f80254b-8dbe-4e84-8410-676b5f489ad7', 'SecureAxpert', 'HR', 200, 2, 'ExtAuth', 'ExtURL', 'EXTAuthRequest', 'EXTAuthRes', true, '{"HR Admin","HR L4"}');


--
-- TOC entry 2845 (class 0 OID 23217)
-- Dependencies: 199
-- Data for Name: ARMUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."ARMUsers" VALUES ('86198c38-e994-4594-917a-8f1ca133743b', 'TestApp2', 'Mohan J', 'drms1120', 'mohanJ@agile-labs.com', '9878762321', 'fa87af77-ac15-42fb-8ef4-3dee603e2480', 'IT Advisor', false, NULL, NULL);
INSERT INTO public."ARMUsers" VALUES ('ba8dacd0-a8a0-43f4-b835-b579f0617306', 'SecureAxpert', 'Deepti', 'Abcd@12345', 'diptimahara8@gmail.com', '9878762321', '5f80254b-8dbe-4e84-8410-676b5f489ad7', 'Admin', true, NULL, NULL);


--
-- TOC entry 2847 (class 0 OID 23227)
-- Dependencies: 201
-- Data for Name: NotificationTemplate; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."NotificationTemplate" VALUES (1, 'WA', 'SignUp_OTP', 'Please provide the following OTP to complete your signup. OTP is {{otp}}.');
INSERT INTO public."NotificationTemplate" VALUES (2, 'SecureAxpert', 'Login_SMS', 'Your temporary authentcated OTP  is {otp}');


--
-- TOC entry 2842 (class 0 OID 23172)
-- Dependencies: 196
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20220902075517_APIDef', '6.0.7');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20220902101508_APIDefs', '6.0.7');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20220902114650_APIDefs01', '6.0.7');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20220905072538_API5sep2022', '6.0.7');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20220905120324_API5sep1733', '6.0.7');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20220905174009_API5sep2309', '6.0.7');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20220906141950_API6sep', '6.0.7');


--
-- TOC entry 2858 (class 0 OID 0)
-- Dependencies: 200
-- Name: NotificationTemplate_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."NotificationTemplate_Id_seq"', 2, true);


--
-- TOC entry 2717 (class 2606 OID 23280)
-- Name: ARMDataSources PK_ARMDataSources; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ARMDataSources"
    ADD CONSTRAINT "PK_ARMDataSources" PRIMARY KEY ("ID");


--
-- TOC entry 2708 (class 2606 OID 23208)
-- Name: ARMDefinations PK_ARMDefinations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ARMDefinations"
    ADD CONSTRAINT "PK_ARMDefinations" PRIMARY KEY ("ID");


--
-- TOC entry 2719 (class 2606 OID 23322)
-- Name: ARMSignInUsers PK_ARMSignInUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ARMSignInUsers"
    ADD CONSTRAINT "PK_ARMSignInUsers" PRIMARY KEY ("Id");


--
-- TOC entry 2710 (class 2606 OID 23216)
-- Name: ARMUserGroups PK_ARMUserGroups; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ARMUserGroups"
    ADD CONSTRAINT "PK_ARMUserGroups" PRIMARY KEY ("ID");


--
-- TOC entry 2712 (class 2606 OID 23224)
-- Name: ARMUsers PK_ARMUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ARMUsers"
    ADD CONSTRAINT "PK_ARMUsers" PRIMARY KEY ("ID");


--
-- TOC entry 2714 (class 2606 OID 23234)
-- Name: NotificationTemplate PK_NotificationTemplate; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."NotificationTemplate"
    ADD CONSTRAINT "PK_NotificationTemplate" PRIMARY KEY ("Id");


--
-- TOC entry 2706 (class 2606 OID 23176)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 2715 (class 1259 OID 23303)
-- Name: IX_ARMDataSources_ARMDataSourceID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ARMDataSources_ARMDataSourceID" ON public."ARMDataSources" USING btree ("ARMDataSourceID");


--
-- TOC entry 2720 (class 2606 OID 23304)
-- Name: ARMDataSources FK_ARMDataSources_ARMDataSources_ARMDataSourceID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ARMDataSources"
    ADD CONSTRAINT "FK_ARMDataSources_ARMDataSources_ARMDataSourceID" FOREIGN KEY ("ARMDataSourceID") REFERENCES public."ARMDataSources"("ID");


-- Completed on 2022-09-19 16:38:39

--
-- PostgreSQL database dump complete
--

